name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: docker-compose pull

      - name: Install dependencies
        run: make composer-install

      - name: Start all the environment
        run: make start

      - name: Wait for the database to get up
        run: |
          while ! make ping-mysql &>/dev/null; do
              echo "Waiting for database connection..."
              sleep 2
          done

      - name: Create Database
        env:
          DATABASE_URL: "mysql://root@127.0.0.1:3360/bookmark_manager?serverVersion=5.7&charset=utf8mb4"
        run: bin/console doctrine:database:create

      - name: Apply migration
        env:
          DATABASE_URL: "mysql://root@127.0.0.1:3360/bookmark_manager?serverVersion=5.7&charset=utf8mb4"
        run: bin/console doctrine:migrations:migrate

      - name: Run the tests
        run: make tests
        env:
          DATABASE_URL: "mysql://root@127.0.0.1:3360/bookmark_manager?serverVersion=5.7&charset=utf8mb4"
